version: '2.1'
services:
  mysql:
    build: ./db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports: 
      - "3351:3306"
    healthcheck:
      test: "exit 0"


  app:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"